### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.rand(10)

In [3]:
vector

array([0.471492  , 0.46029473, 0.76323197, 0.04821755, 0.02970084,
       0.73243034, 0.57852661, 0.6058253 , 0.61557482, 0.7588365 ])

In [4]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])

In [5]:
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [6]:
vector_plus_10 = np.round(vector + 10, 2)
vector_plus_10

array([10.47, 10.46, 10.76, 10.05, 10.03, 10.73, 10.58, 10.61, 10.62,
       10.76])

In [7]:
matrix_x_2 = np.dot(matrix, 2)
matrix_x_2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [8]:
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [9]:
vector_sqr = vector ** 2
vector_sqr

array([0.22230471, 0.21187124, 0.58252304, 0.00232493, 0.00088214,
       0.53645421, 0.33469304, 0.3670243 , 0.37893236, 0.57583283])

In [10]:
np.square(vector)

array([0.22230471, 0.21187124, 0.58252304, 0.00232493, 0.00088214,
       0.53645421, 0.33469304, 0.3670243 , 0.37893236, 0.57583283])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [11]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [12]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [13]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [14]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [15]:
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [16]:
result_matrix_t = result_matrix.T
result_matrix_t

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [17]:
vector

array([0.471492  , 0.46029473, 0.76323197, 0.04821755, 0.02970084,
       0.73243034, 0.57852661, 0.6058253 , 0.61557482, 0.7588365 ])

In [18]:
vector.shape

(10,)

In [19]:
vector.T

array([0.471492  , 0.46029473, 0.76323197, 0.04821755, 0.02970084,
       0.73243034, 0.57852661, 0.6058253 , 0.61557482, 0.7588365 ])

In [20]:
vector.T.shape

(10,)

різниці немає тому що `vector` одновимірний масив

In [21]:
column_vector = np.expand_dims(vector, axis=1)
column_vector

array([[0.471492  ],
       [0.46029473],
       [0.76323197],
       [0.04821755],
       [0.02970084],
       [0.73243034],
       [0.57852661],
       [0.6058253 ],
       [0.61557482],
       [0.7588365 ]])

In [22]:
column_vector.shape

(10, 1)

`column_vector` став двовимірним масивом

In [23]:
column_vector.T

array([[0.471492  , 0.46029473, 0.76323197, 0.04821755, 0.02970084,
        0.73243034, 0.57852661, 0.6058253 , 0.61557482, 0.7588365 ]])

In [24]:
column_vector.T.shape

(1, 10)